name: PlayCY-GameManager
main: ca.kanoa.playcy.gamemanager.PlayCY
version: 0.00.0000
author: 12323op
commands:
    playcy:
        description: PlayCY main plugin command base
        usage: /playcy <version/addloc>
        aliases: [sign, signs, cy]